# 手書き数字認識

In [2]:
import sys, os
sys.path.append(os.getcwd() + '/oreilly')
from dataset.mnist import load_mnist

(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

print(x_train.shape)
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)

Done
Done
Done
Done
Converting train-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting train-labels-idx1-ubyte.gz to NumPy Array ...
Done
Converting t10k-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting t10k-labels-idx1-ubyte.gz to NumPy Array ...
Done
Creating pickle file ...
Done!
(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [4]:
import numpy as np 
import pickle

def get_data():
    (x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)
    return x_test, t_test

def init_network():
    with open(os.getcwd() + "/oreilly/ch03/sample_weight.pkl", 'rb') as f:
        network = pickle.load(f)
        
    return network

def sigmoid(x):
    sigmoid_range = 34.538776394910684
    work_x = x
    
    for i, row in enumerate(x):
        for j, e in enumerate(row):
            if e <= -sigmoid_range:
                work_x[i][j] = 1e-15

        for j, e in enumerate(row):
            if e >= sigmoid_range:
                work_x[i][j] = 1.0 - 1e-15
    
    return 1.0 / (1.0 + np.exp(-work_x))

def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c) # オーバーフロー対策
    sum_exp_a = np.sum(exp_a)
    return exp_a / sum_exp_a

def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)
    
    return y


In [ ]:
x, t = get_data()
network = init_network()

accuracy_cnt = 0
for i in range(len(x)):
    y = predict(network, x[i])
    
    p = np.argmax(y) # 最も確率の高い要素のインデックスを取得
    if p == t[i]:
        accuracy_cnt += 1
        
print("Accuracy:" + str(float(accuracy_cnt) / len(x)))


In [14]:
x, _ = get_data()
network = init_network()
W1, W2, W3 = network['W1'], network['W2'], network['W3']

print(x)
print(x.shape) # 10000行、784列
print(x[0].shape) # xの行数
print(x[1].shape) # xの列数
print(W1.shape)
print(W2.shape)
print(W3.shape)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(10000, 784)
(784,)
(784,)
(784, 50)
(50, 100)
(100, 10)


In [52]:
x, t = get_data()
network = init_network()

batch_size = 100
accuracy_cnt = 0

for i in range(0, len(x), batch_size):
    x_batch = x[i:i+batch_size] # 先頭から100枚ずつバッチを取り出す
    y_batch = predict(network, x_batch)
    
    p = np.argmax(y_batch, axis=1) # 最も確率の高い要素のインデックスを取得
    accuracy_cnt += np.sum(p == t[i:i+batch_size])

print("Accuracy:" + str(float(accuracy_cnt) / len(x)))


Accuracy:0.4209


In [1]:
# startからend - 1のリストを作る
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
# stepで指定された値だけ増加するリストを作る
list(range(0, 10, 3))

[0, 3, 6, 9]

In [11]:
x = np.array([
    [0.1, 0.8, 0.1],
    [0.3, 0.1, 0.6],
    [0.2, 0.5, 0.3],
    [0.9, 0.1, 0.6]
])

y = np.argmax(x, axis=1)
print(y)  # 0.8 0.6 0.5 0.9。各行の最大値のインデックスを返す

y2 = np.argmax(x)
print(y2)  # 0.9のインデックスを返す。一次元にして最大値のインデックスを返す

y3 = np.argmax(x, axis=0)
print(y3)  # 縦方向にそれぞれの最大値のインデックスを返す

[1 2 1 0]
9
[3 0 1]


In [15]:
y = np.array([1, 2, 1, 0, 2])
t = np.array([1, 2, 0, 0, 2])

print(y == t)  # 各要素を比較してTrue, Falseがつまった配列を返す

np.sum(y == t) # Trueの数を返す


[ True  True False  True  True]


4