In [8]:
# 入力層から第一層への信号の伝達
import numpy as np

X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

A1 = np.dot(X, W1) + B1
print(A1)

print(np.dot(X, W1))

def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

Z1 = sigmoid(A1)

print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.2 0.5 0.8]
[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [9]:
# 第一層から第二層への信号の伝達
# 第一層のニューロンは３個（なので重みも３個）、第二層は2個（結果も2列になる。手計算で確認した）

W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

print(np.dot(np.array([0.5,0.6,0.7]), W2))
print(np.dot(Z1, W2))
print(A2)
print(Z2)

[0.38 0.92]
[0.41615984 1.01402696]
[0.51615984 1.21402696]
[0.62624937 0.7710107 ]


In [10]:
# 第二層から結果層へ

def identify_function(x):
    return x

W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B2
Y = identify_function(A3)

print(Y)

[0.31682708 0.69627909]


In [11]:
# 実装のまとめ

def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    return  network
    
def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identify_function(a3)
    return y

    
network = init_network()
print(network)
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)


{'W1': array([[0.1, 0.3, 0.5],
       [0.2, 0.4, 0.6]]), 'b1': array([0.1, 0.2, 0.3]), 'W2': array([[0.1, 0.4],
       [0.2, 0.5],
       [0.3, 0.6]]), 'b2': array([0.1, 0.2]), 'W3': array([[0.1, 0.3],
       [0.2, 0.4]]), 'b3': array([0.1, 0.2])}
[0.31682708 0.69627909]


In [13]:
# ソフトマックス関数

def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c) # オーバーフロー対策
    sum_exp_a = np.sum(exp_a)
    return exp_a / sum_exp_a

a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)

# ソフトマックス関数の結果は全て足すと１になる
print(np.sum(y))

[0.01821127 0.24519181 0.73659691]
1.0
