In [9]:
# 入力層から第一層への信号の伝達
import numpy as np

X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

A1 = np.dot(X, W1) + B1
print A1

print np.dot(X, W1)

def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

Z1 = sigmoid(A1)

print(A1)
print(Z1)

[ 0.3  0.7  1.1]
[ 0.2  0.5  0.8]
[ 0.3  0.7  1.1]
[ 0.57444252  0.66818777  0.75026011]


In [10]:
# 第一層から第二層への信号の伝達
# 第一層のニューロンは３個（なので重みも３個）、第二層は2個

W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

print(np.dot(np.array([0.5,0.6,0.7]), W2))
print(np.dot(Z1, W2))
print(A2)
print(Z2)

[ 0.38  0.92]
[ 0.41615984  1.01402696]
[ 0.51615984  1.21402696]
[ 0.62624937  0.7710107 ]
