# 4章 ニューラルネットワークの学習

## 損失関数
### 二乗和誤差

In [ ]:
import numpy as np

# t: 教師データ
# index 2を正解とする
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

# y: ニューラルネットワークの出力
# 例1.「2」の確率が最も高い場合(0.6)
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]

# 二乗和誤差
def mean_squared_error(y, t):
    return 0.5 * np.sum((y - t) ** 2)

# np.arrayはsumに渡すために変換をしている
mean_squared_error(np.array(y), np.array(t))
# => 0.0975000...31

# 例2.「7」の確率が最も高い場合(0.6)
y = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.0, 0.0]
mean_squared_error(np.array(y), np.array(t))
# => 0.59750...3

# 2つの結果でわかることは、教師データとの誤差を表している
# 例1の結果のほうが値が小さいので誤差が小さいことがわかる。


### 交差エントロピー誤差

In [ ]:
def cross_entropy_error(y, t):
    delta = 1e-7
    return -np.sum(t * np.log(y + delta))

t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
a = cross_entropy_error(np.array(y), np.array(t))
print(a)
# => 0.510825457099

y = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.0, 0.0]
b = cross_entropy_error(np.array(y), np.array(t))
print(b)
# => 2.30258409299


# こちらも1番目の結果の方が値が小さいので誤差が小さいと判断する

In [ ]:
np.random.choice(60000, 10)

In [2]:
import numpy as np
import sys, os
sys.path.append(os.getcwd() + '/oreilly')
from dataset.mnist import load_mnist

# y : ニューラルネットワーク出力
# t : 教師データ
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, t.size)
        
    batch_size = y.shape[0]
    # バッチ枚数で正規化し、1枚あたりの平均の交差エントロピー誤差を計算する
    return -np.sum(t * np.log(y + delta)) / batch_size

# load_mnist内の関数（_change_one_hot_label）の定義側にtypoがあった
(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, one_hot_label=True)

train_size = x_train.shape[0]
batch_size = 10
batch_mask = np.random.choice(train_size, batch_size)
x_batch = x_train[batch_mask]
t_batch = t_train[batch_mask]

print('x_batch : %s', x_batch)
print('t_batch : %s', t_batch)


x_batch : %s [[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
t_batch : %s [[ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]]
